all:  var1c var1cpp varmutex semaphore
var1c:
	gcc var.c -o 1.out
	./1.out
var1cpp:
	g++ var.cpp -o 1.cpp.out
	./1.cpp.out
varmutex:
	gcc varmutex.c -o 2.out
	./2.out
semaphore:
	gcc semaphore.c -o 3.out
	./3.out
